splash = false

wallpaper {
  monitor =
  path = ~/.local/share/backgrounds/black_and_white_architecture
  fit_mode = contain
  order = random
  timeout = 180
}

wallpaper {
  monitor = DP-2
  path = ~/.local/share/backgrounds/black_and_white_architecture/photo-1498690426516-2cdc03792da8.jpg
  fit_mode = contain
}

