# Warning: This config does not include keys that have an unset value
format = """
   \
$username\
${custom.hostname}\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$haskell\
$java\
$nodejs\
$kotlin\
$php\
$python\
$rust\
$fill\
$all\
$line_break\
$shell\
$battery\
$time\
$jobs\
$status\
$character"""

[aws]
symbol = "aws "
format = "via [$symbol]($style)"

[directory]
truncate_to_repo = false
format = "[\\\\\\\\ $path ]($style)[($read_only )]($read_only_style)[\\\\\\\\](fg:254) "
style = 'cyan bold'
read_only = 'LOCK'
read_only_style = 'red'
truncation_length = 3

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[haskell]
format = "via [$symbol]($style)"
symbol = "hs "

[java]
format = "via [$symbol]($style)"
symbol = "java "

[kotlin]
format = "via [$symbol]($style)"
symbol = "kt "

[nodejs]
format = "via [$symbol]($style)"
symbol = "nodejs  "

[php]
format = "via [$symbol]($style)"
symbol = "php "

[python]
format = "via [$symbol]($style)"
symbol = "py "

[rust]
format = "via [$symbol]($style)"
symbol = "rs "

[[battery.display]]
threshold = 10
style = 'red bold'

[character]
format = '$symbol '
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
vicmd_symbol = '[<](bold green)'
disabled = false

[jobs]
format = "[\\\\\\\\ $symbol$number ]($style)"

[shell]
format = "[$indicator ](bold fg:135)[\\\\\\\\ ](fg:254)"
bash_indicator = ' \$_'
disabled = false

[status]
format = "[\\\\\\\\ $status (\\($common_meaning\\) )]($style)"
disabled = false

[time]
format = "[$time ]($style)"

[username]
format = "[\\\\\\\\ $user ]($style)"
style_root = "bold red"
style_user = "bold fg:254"
show_always = true

[custom]

[custom.hostname]
command = "hostnamectl --static status"
when = "true"
format = "[\\\\\\\\ $output ]($style)"
style = "bold fg:207"

