#!/usr/bin/env sh

icons=10
slotSize=28
primaryHorizontalOffset=$(xrandr -q | rg ' connected primary' | cut -d' ' -f4 | sed 's/[x]/\+/g' | cut -d'+' -f 1,3 | bc -l)
stalonetrayOffset=$(expr "$primaryHorizontalOffset" - "$icons" \* "$slotSize" - 0)
stalonetrayPID=$(pidof stalonetray)

if [ $? -eq 0 ]; then
  kill $stalonetrayPID
fi

nohup stalonetray --geometry "$icons"x1+"$stalonetrayOffset"+2 --config ~/.config/stalonetrayrc >> /tmp/stalonetray_$USER 2>&1 &

